/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretariaRouteImport } from './routes/secretaria'
import { Route as PrefeitoRouteImport } from './routes/prefeito'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GovernadorRouteImport } from './routes/governador'
import { Route as CidadaoRouteImport } from './routes/cidadao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrefeitoIndexRouteImport } from './routes/prefeito.index'
import { Route as PrefeitoSocialRouteImport } from './routes/prefeito.social'
import { Route as PrefeitoRelatoriosRouteImport } from './routes/prefeito.relatorios'
import { Route as PrefeitoIntegracoesRouteImport } from './routes/prefeito.integracoes'
import { Route as PrefeitoCaptacaoRouteImport } from './routes/prefeito.captacao'
import { Route as PrefeitoBenchmarkRouteImport } from './routes/prefeito.benchmark'
import { Route as CidadaoServicosRouteImport } from './routes/cidadao.servicos'
import { Route as CidadaoSaudeRouteImport } from './routes/cidadao.saude'
import { Route as CidadaoPerfilRouteImport } from './routes/cidadao.perfil'
import { Route as CidadaoEducacaoRouteImport } from './routes/cidadao.educacao'
import { Route as PainelSecretariaSlugRouteImport } from './routes/painel.secretaria.$slug'
import { Route as GovernadorSecretariaSlugRouteImport } from './routes/governador.secretaria.$slug'
import { Route as CidadaoServicosSolicitarRouteImport } from './routes/cidadao.servicos.solicitar'
import { Route as CidadaoServicosOuvidoriaRouteImport } from './routes/cidadao.servicos.ouvidoria'
import { Route as CidadaoSaudeAgendarRouteImport } from './routes/cidadao.saude.agendar'
import { Route as CidadaoEducacaoMatricularRouteImport } from './routes/cidadao.educacao.matricular'
import { Route as CidadaoDemandaIdRouteImport } from './routes/cidadao.demanda.$id'

const SecretariaRoute = SecretariaRouteImport.update({
  id: '/secretaria',
  path: '/secretaria',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefeitoRoute = PrefeitoRouteImport.update({
  id: '/prefeito',
  path: '/prefeito',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernadorRoute = GovernadorRouteImport.update({
  id: '/governador',
  path: '/governador',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoRoute = CidadaoRouteImport.update({
  id: '/cidadao',
  path: '/cidadao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefeitoIndexRoute = PrefeitoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrefeitoRoute,
} as any)
const PrefeitoSocialRoute = PrefeitoSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => PrefeitoRoute,
} as any)
const PrefeitoRelatoriosRoute = PrefeitoRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PrefeitoRoute,
} as any)
const PrefeitoIntegracoesRoute = PrefeitoIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => PrefeitoRoute,
} as any)
const PrefeitoCaptacaoRoute = PrefeitoCaptacaoRouteImport.update({
  id: '/captacao',
  path: '/captacao',
  getParentRoute: () => PrefeitoRoute,
} as any)
const PrefeitoBenchmarkRoute = PrefeitoBenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => PrefeitoRoute,
} as any)
const CidadaoServicosRoute = CidadaoServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => CidadaoRoute,
} as any)
const CidadaoSaudeRoute = CidadaoSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => CidadaoRoute,
} as any)
const CidadaoPerfilRoute = CidadaoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CidadaoRoute,
} as any)
const CidadaoEducacaoRoute = CidadaoEducacaoRouteImport.update({
  id: '/educacao',
  path: '/educacao',
  getParentRoute: () => CidadaoRoute,
} as any)
const PainelSecretariaSlugRoute = PainelSecretariaSlugRouteImport.update({
  id: '/painel/secretaria/$slug',
  path: '/painel/secretaria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernadorSecretariaSlugRoute =
  GovernadorSecretariaSlugRouteImport.update({
    id: '/secretaria/$slug',
    path: '/secretaria/$slug',
    getParentRoute: () => GovernadorRoute,
  } as any)
const CidadaoServicosSolicitarRoute =
  CidadaoServicosSolicitarRouteImport.update({
    id: '/solicitar',
    path: '/solicitar',
    getParentRoute: () => CidadaoServicosRoute,
  } as any)
const CidadaoServicosOuvidoriaRoute =
  CidadaoServicosOuvidoriaRouteImport.update({
    id: '/ouvidoria',
    path: '/ouvidoria',
    getParentRoute: () => CidadaoServicosRoute,
  } as any)
const CidadaoSaudeAgendarRoute = CidadaoSaudeAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => CidadaoSaudeRoute,
} as any)
const CidadaoEducacaoMatricularRoute =
  CidadaoEducacaoMatricularRouteImport.update({
    id: '/matricular',
    path: '/matricular',
    getParentRoute: () => CidadaoEducacaoRoute,
  } as any)
const CidadaoDemandaIdRoute = CidadaoDemandaIdRouteImport.update({
  id: '/demanda/$id',
  path: '/demanda/$id',
  getParentRoute: () => CidadaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cidadao': typeof CidadaoRouteWithChildren
  '/governador': typeof GovernadorRouteWithChildren
  '/login': typeof LoginRoute
  '/prefeito': typeof PrefeitoRouteWithChildren
  '/secretaria': typeof SecretariaRoute
  '/cidadao/educacao': typeof CidadaoEducacaoRouteWithChildren
  '/cidadao/perfil': typeof CidadaoPerfilRoute
  '/cidadao/saude': typeof CidadaoSaudeRouteWithChildren
  '/cidadao/servicos': typeof CidadaoServicosRouteWithChildren
  '/prefeito/benchmark': typeof PrefeitoBenchmarkRoute
  '/prefeito/captacao': typeof PrefeitoCaptacaoRoute
  '/prefeito/integracoes': typeof PrefeitoIntegracoesRoute
  '/prefeito/relatorios': typeof PrefeitoRelatoriosRoute
  '/prefeito/social': typeof PrefeitoSocialRoute
  '/prefeito/': typeof PrefeitoIndexRoute
  '/cidadao/demanda/$id': typeof CidadaoDemandaIdRoute
  '/cidadao/educacao/matricular': typeof CidadaoEducacaoMatricularRoute
  '/cidadao/saude/agendar': typeof CidadaoSaudeAgendarRoute
  '/cidadao/servicos/ouvidoria': typeof CidadaoServicosOuvidoriaRoute
  '/cidadao/servicos/solicitar': typeof CidadaoServicosSolicitarRoute
  '/governador/secretaria/$slug': typeof GovernadorSecretariaSlugRoute
  '/painel/secretaria/$slug': typeof PainelSecretariaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cidadao': typeof CidadaoRouteWithChildren
  '/governador': typeof GovernadorRouteWithChildren
  '/login': typeof LoginRoute
  '/secretaria': typeof SecretariaRoute
  '/cidadao/educacao': typeof CidadaoEducacaoRouteWithChildren
  '/cidadao/perfil': typeof CidadaoPerfilRoute
  '/cidadao/saude': typeof CidadaoSaudeRouteWithChildren
  '/cidadao/servicos': typeof CidadaoServicosRouteWithChildren
  '/prefeito/benchmark': typeof PrefeitoBenchmarkRoute
  '/prefeito/captacao': typeof PrefeitoCaptacaoRoute
  '/prefeito/integracoes': typeof PrefeitoIntegracoesRoute
  '/prefeito/relatorios': typeof PrefeitoRelatoriosRoute
  '/prefeito/social': typeof PrefeitoSocialRoute
  '/prefeito': typeof PrefeitoIndexRoute
  '/cidadao/demanda/$id': typeof CidadaoDemandaIdRoute
  '/cidadao/educacao/matricular': typeof CidadaoEducacaoMatricularRoute
  '/cidadao/saude/agendar': typeof CidadaoSaudeAgendarRoute
  '/cidadao/servicos/ouvidoria': typeof CidadaoServicosOuvidoriaRoute
  '/cidadao/servicos/solicitar': typeof CidadaoServicosSolicitarRoute
  '/governador/secretaria/$slug': typeof GovernadorSecretariaSlugRoute
  '/painel/secretaria/$slug': typeof PainelSecretariaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cidadao': typeof CidadaoRouteWithChildren
  '/governador': typeof GovernadorRouteWithChildren
  '/login': typeof LoginRoute
  '/prefeito': typeof PrefeitoRouteWithChildren
  '/secretaria': typeof SecretariaRoute
  '/cidadao/educacao': typeof CidadaoEducacaoRouteWithChildren
  '/cidadao/perfil': typeof CidadaoPerfilRoute
  '/cidadao/saude': typeof CidadaoSaudeRouteWithChildren
  '/cidadao/servicos': typeof CidadaoServicosRouteWithChildren
  '/prefeito/benchmark': typeof PrefeitoBenchmarkRoute
  '/prefeito/captacao': typeof PrefeitoCaptacaoRoute
  '/prefeito/integracoes': typeof PrefeitoIntegracoesRoute
  '/prefeito/relatorios': typeof PrefeitoRelatoriosRoute
  '/prefeito/social': typeof PrefeitoSocialRoute
  '/prefeito/': typeof PrefeitoIndexRoute
  '/cidadao/demanda/$id': typeof CidadaoDemandaIdRoute
  '/cidadao/educacao/matricular': typeof CidadaoEducacaoMatricularRoute
  '/cidadao/saude/agendar': typeof CidadaoSaudeAgendarRoute
  '/cidadao/servicos/ouvidoria': typeof CidadaoServicosOuvidoriaRoute
  '/cidadao/servicos/solicitar': typeof CidadaoServicosSolicitarRoute
  '/governador/secretaria/$slug': typeof GovernadorSecretariaSlugRoute
  '/painel/secretaria/$slug': typeof PainelSecretariaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cidadao'
    | '/governador'
    | '/login'
    | '/prefeito'
    | '/secretaria'
    | '/cidadao/educacao'
    | '/cidadao/perfil'
    | '/cidadao/saude'
    | '/cidadao/servicos'
    | '/prefeito/benchmark'
    | '/prefeito/captacao'
    | '/prefeito/integracoes'
    | '/prefeito/relatorios'
    | '/prefeito/social'
    | '/prefeito/'
    | '/cidadao/demanda/$id'
    | '/cidadao/educacao/matricular'
    | '/cidadao/saude/agendar'
    | '/cidadao/servicos/ouvidoria'
    | '/cidadao/servicos/solicitar'
    | '/governador/secretaria/$slug'
    | '/painel/secretaria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cidadao'
    | '/governador'
    | '/login'
    | '/secretaria'
    | '/cidadao/educacao'
    | '/cidadao/perfil'
    | '/cidadao/saude'
    | '/cidadao/servicos'
    | '/prefeito/benchmark'
    | '/prefeito/captacao'
    | '/prefeito/integracoes'
    | '/prefeito/relatorios'
    | '/prefeito/social'
    | '/prefeito'
    | '/cidadao/demanda/$id'
    | '/cidadao/educacao/matricular'
    | '/cidadao/saude/agendar'
    | '/cidadao/servicos/ouvidoria'
    | '/cidadao/servicos/solicitar'
    | '/governador/secretaria/$slug'
    | '/painel/secretaria/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cidadao'
    | '/governador'
    | '/login'
    | '/prefeito'
    | '/secretaria'
    | '/cidadao/educacao'
    | '/cidadao/perfil'
    | '/cidadao/saude'
    | '/cidadao/servicos'
    | '/prefeito/benchmark'
    | '/prefeito/captacao'
    | '/prefeito/integracoes'
    | '/prefeito/relatorios'
    | '/prefeito/social'
    | '/prefeito/'
    | '/cidadao/demanda/$id'
    | '/cidadao/educacao/matricular'
    | '/cidadao/saude/agendar'
    | '/cidadao/servicos/ouvidoria'
    | '/cidadao/servicos/solicitar'
    | '/governador/secretaria/$slug'
    | '/painel/secretaria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CidadaoRoute: typeof CidadaoRouteWithChildren
  GovernadorRoute: typeof GovernadorRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrefeitoRoute: typeof PrefeitoRouteWithChildren
  SecretariaRoute: typeof SecretariaRoute
  PainelSecretariaSlugRoute: typeof PainelSecretariaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretaria': {
      id: '/secretaria'
      path: '/secretaria'
      fullPath: '/secretaria'
      preLoaderRoute: typeof SecretariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefeito': {
      id: '/prefeito'
      path: '/prefeito'
      fullPath: '/prefeito'
      preLoaderRoute: typeof PrefeitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governador': {
      id: '/governador'
      path: '/governador'
      fullPath: '/governador'
      preLoaderRoute: typeof GovernadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao': {
      id: '/cidadao'
      path: '/cidadao'
      fullPath: '/cidadao'
      preLoaderRoute: typeof CidadaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefeito/': {
      id: '/prefeito/'
      path: '/'
      fullPath: '/prefeito/'
      preLoaderRoute: typeof PrefeitoIndexRouteImport
      parentRoute: typeof PrefeitoRoute
    }
    '/prefeito/social': {
      id: '/prefeito/social'
      path: '/social'
      fullPath: '/prefeito/social'
      preLoaderRoute: typeof PrefeitoSocialRouteImport
      parentRoute: typeof PrefeitoRoute
    }
    '/prefeito/relatorios': {
      id: '/prefeito/relatorios'
      path: '/relatorios'
      fullPath: '/prefeito/relatorios'
      preLoaderRoute: typeof PrefeitoRelatoriosRouteImport
      parentRoute: typeof PrefeitoRoute
    }
    '/prefeito/integracoes': {
      id: '/prefeito/integracoes'
      path: '/integracoes'
      fullPath: '/prefeito/integracoes'
      preLoaderRoute: typeof PrefeitoIntegracoesRouteImport
      parentRoute: typeof PrefeitoRoute
    }
    '/prefeito/captacao': {
      id: '/prefeito/captacao'
      path: '/captacao'
      fullPath: '/prefeito/captacao'
      preLoaderRoute: typeof PrefeitoCaptacaoRouteImport
      parentRoute: typeof PrefeitoRoute
    }
    '/prefeito/benchmark': {
      id: '/prefeito/benchmark'
      path: '/benchmark'
      fullPath: '/prefeito/benchmark'
      preLoaderRoute: typeof PrefeitoBenchmarkRouteImport
      parentRoute: typeof PrefeitoRoute
    }
    '/cidadao/servicos': {
      id: '/cidadao/servicos'
      path: '/servicos'
      fullPath: '/cidadao/servicos'
      preLoaderRoute: typeof CidadaoServicosRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/cidadao/saude': {
      id: '/cidadao/saude'
      path: '/saude'
      fullPath: '/cidadao/saude'
      preLoaderRoute: typeof CidadaoSaudeRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/cidadao/perfil': {
      id: '/cidadao/perfil'
      path: '/perfil'
      fullPath: '/cidadao/perfil'
      preLoaderRoute: typeof CidadaoPerfilRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/cidadao/educacao': {
      id: '/cidadao/educacao'
      path: '/educacao'
      fullPath: '/cidadao/educacao'
      preLoaderRoute: typeof CidadaoEducacaoRouteImport
      parentRoute: typeof CidadaoRoute
    }
    '/painel/secretaria/$slug': {
      id: '/painel/secretaria/$slug'
      path: '/painel/secretaria/$slug'
      fullPath: '/painel/secretaria/$slug'
      preLoaderRoute: typeof PainelSecretariaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governador/secretaria/$slug': {
      id: '/governador/secretaria/$slug'
      path: '/secretaria/$slug'
      fullPath: '/governador/secretaria/$slug'
      preLoaderRoute: typeof GovernadorSecretariaSlugRouteImport
      parentRoute: typeof GovernadorRoute
    }
    '/cidadao/servicos/solicitar': {
      id: '/cidadao/servicos/solicitar'
      path: '/solicitar'
      fullPath: '/cidadao/servicos/solicitar'
      preLoaderRoute: typeof CidadaoServicosSolicitarRouteImport
      parentRoute: typeof CidadaoServicosRoute
    }
    '/cidadao/servicos/ouvidoria': {
      id: '/cidadao/servicos/ouvidoria'
      path: '/ouvidoria'
      fullPath: '/cidadao/servicos/ouvidoria'
      preLoaderRoute: typeof CidadaoServicosOuvidoriaRouteImport
      parentRoute: typeof CidadaoServicosRoute
    }
    '/cidadao/saude/agendar': {
      id: '/cidadao/saude/agendar'
      path: '/agendar'
      fullPath: '/cidadao/saude/agendar'
      preLoaderRoute: typeof CidadaoSaudeAgendarRouteImport
      parentRoute: typeof CidadaoSaudeRoute
    }
    '/cidadao/educacao/matricular': {
      id: '/cidadao/educacao/matricular'
      path: '/matricular'
      fullPath: '/cidadao/educacao/matricular'
      preLoaderRoute: typeof CidadaoEducacaoMatricularRouteImport
      parentRoute: typeof CidadaoEducacaoRoute
    }
    '/cidadao/demanda/$id': {
      id: '/cidadao/demanda/$id'
      path: '/demanda/$id'
      fullPath: '/cidadao/demanda/$id'
      preLoaderRoute: typeof CidadaoDemandaIdRouteImport
      parentRoute: typeof CidadaoRoute
    }
  }
}

interface CidadaoEducacaoRouteChildren {
  CidadaoEducacaoMatricularRoute: typeof CidadaoEducacaoMatricularRoute
}

const CidadaoEducacaoRouteChildren: CidadaoEducacaoRouteChildren = {
  CidadaoEducacaoMatricularRoute: CidadaoEducacaoMatricularRoute,
}

const CidadaoEducacaoRouteWithChildren = CidadaoEducacaoRoute._addFileChildren(
  CidadaoEducacaoRouteChildren,
)

interface CidadaoSaudeRouteChildren {
  CidadaoSaudeAgendarRoute: typeof CidadaoSaudeAgendarRoute
}

const CidadaoSaudeRouteChildren: CidadaoSaudeRouteChildren = {
  CidadaoSaudeAgendarRoute: CidadaoSaudeAgendarRoute,
}

const CidadaoSaudeRouteWithChildren = CidadaoSaudeRoute._addFileChildren(
  CidadaoSaudeRouteChildren,
)

interface CidadaoServicosRouteChildren {
  CidadaoServicosOuvidoriaRoute: typeof CidadaoServicosOuvidoriaRoute
  CidadaoServicosSolicitarRoute: typeof CidadaoServicosSolicitarRoute
}

const CidadaoServicosRouteChildren: CidadaoServicosRouteChildren = {
  CidadaoServicosOuvidoriaRoute: CidadaoServicosOuvidoriaRoute,
  CidadaoServicosSolicitarRoute: CidadaoServicosSolicitarRoute,
}

const CidadaoServicosRouteWithChildren = CidadaoServicosRoute._addFileChildren(
  CidadaoServicosRouteChildren,
)

interface CidadaoRouteChildren {
  CidadaoEducacaoRoute: typeof CidadaoEducacaoRouteWithChildren
  CidadaoPerfilRoute: typeof CidadaoPerfilRoute
  CidadaoSaudeRoute: typeof CidadaoSaudeRouteWithChildren
  CidadaoServicosRoute: typeof CidadaoServicosRouteWithChildren
  CidadaoDemandaIdRoute: typeof CidadaoDemandaIdRoute
}

const CidadaoRouteChildren: CidadaoRouteChildren = {
  CidadaoEducacaoRoute: CidadaoEducacaoRouteWithChildren,
  CidadaoPerfilRoute: CidadaoPerfilRoute,
  CidadaoSaudeRoute: CidadaoSaudeRouteWithChildren,
  CidadaoServicosRoute: CidadaoServicosRouteWithChildren,
  CidadaoDemandaIdRoute: CidadaoDemandaIdRoute,
}

const CidadaoRouteWithChildren =
  CidadaoRoute._addFileChildren(CidadaoRouteChildren)

interface GovernadorRouteChildren {
  GovernadorSecretariaSlugRoute: typeof GovernadorSecretariaSlugRoute
}

const GovernadorRouteChildren: GovernadorRouteChildren = {
  GovernadorSecretariaSlugRoute: GovernadorSecretariaSlugRoute,
}

const GovernadorRouteWithChildren = GovernadorRoute._addFileChildren(
  GovernadorRouteChildren,
)

interface PrefeitoRouteChildren {
  PrefeitoBenchmarkRoute: typeof PrefeitoBenchmarkRoute
  PrefeitoCaptacaoRoute: typeof PrefeitoCaptacaoRoute
  PrefeitoIntegracoesRoute: typeof PrefeitoIntegracoesRoute
  PrefeitoRelatoriosRoute: typeof PrefeitoRelatoriosRoute
  PrefeitoSocialRoute: typeof PrefeitoSocialRoute
  PrefeitoIndexRoute: typeof PrefeitoIndexRoute
}

const PrefeitoRouteChildren: PrefeitoRouteChildren = {
  PrefeitoBenchmarkRoute: PrefeitoBenchmarkRoute,
  PrefeitoCaptacaoRoute: PrefeitoCaptacaoRoute,
  PrefeitoIntegracoesRoute: PrefeitoIntegracoesRoute,
  PrefeitoRelatoriosRoute: PrefeitoRelatoriosRoute,
  PrefeitoSocialRoute: PrefeitoSocialRoute,
  PrefeitoIndexRoute: PrefeitoIndexRoute,
}

const PrefeitoRouteWithChildren = PrefeitoRoute._addFileChildren(
  PrefeitoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CidadaoRoute: CidadaoRouteWithChildren,
  GovernadorRoute: GovernadorRouteWithChildren,
  LoginRoute: LoginRoute,
  PrefeitoRoute: PrefeitoRouteWithChildren,
  SecretariaRoute: SecretariaRoute,
  PainelSecretariaSlugRoute: PainelSecretariaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
