DELETE FROM public.alertas_prazos WHERE criado_automaticamente = true;

INSERT INTO public.alertas_prazos (tenant_id, titulo, descricao, tipo, fonte, valor_estimado, prazo, status, requisitos, url_edital, criado_automaticamente)
SELECT
  t.id, d.titulo, d.descricao, d.tipo::alerta_tipo, d.fonte, d.valor, d.prazo::DATE, d.status::alerta_status, d.requisitos::JSONB, d.url_edital, true
FROM public.tenants t
CROSS JOIN (VALUES
  ('FNDE — PDDE Emergencial 2025','Programa Dinheiro Direto na Escola — recursos para manutenção de escolas municipais','recurso_federal','FNDE/MEC',280000,(CURRENT_DATE + INTERVAL '8 days')::text,'em_risco','[{"item":"Plano de trabalho","concluido":true},{"item":"Declaração do gestor","concluido":true},{"item":"Certidão negativa débitos","concluido":true},{"item":"Relatório execução anterior","concluido":false},{"item":"Termo de aceite PDDE.gov.br","concluido":false}]','https://www.fnde.gov.br/pdde'),
  ('MS — Atenção Básica Municipal 2025','Componente de Atenção Básica do Piso da Atenção Básica — custeio UBS','recurso_federal','Ministério da Saúde',145000,(CURRENT_DATE + INTERVAL '12 days')::text,'em_risco','[{"item":"Cadastro SCNES atualizado","concluido":true},{"item":"RREO enviado ao SIOPS","concluido":false},{"item":"Equipe mínima ACS cadastrada","concluido":true}]','https://aps.saude.gov.br'),
  ('MDR — Pavimentação Urbana (PA-Rural)','Programa de Pavimentação e Qualificação de Calçadas — municípios até 50k hab','recurso_federal','Min. Desenvolvimento Regional',890000,(CURRENT_DATE + INTERVAL '90 days')::text,'em_andamento','[{"item":"Projeto executivo aprovado","concluido":true},{"item":"Licença ambiental","concluido":true},{"item":"Contrapartida municipal confirmada","concluido":true},{"item":"Ordem de serviço emitida","concluido":true},{"item":"Relatório parcial 50%","concluido":false}]','https://www.gov.br/mdr'),
  ('MEC — Escola em Tempo Integral 2025','Programa Escola em Tempo Integral — ampliação da jornada escolar','recurso_federal','MEC',420000,(CURRENT_DATE + INTERVAL '45 days')::text,'disponivel','[{"item":"Adesão no SIMEC","concluido":false},{"item":"Levantamento de escolas elegíveis","concluido":false},{"item":"Plano de implementação","concluido":false}]','https://www.gov.br/mec/escola-tempo-integral'),
  ('MAPA — Agricultura Familiar Municipal','PAA — Programa de Aquisição de Alimentos para merenda escolar','recurso_federal','MAPA/CONAB',95000,(CURRENT_DATE + INTERVAL '60 days')::text,'disponivel','[{"item":"Mapeamento produtores locais DAP","concluido":false},{"item":"Chamada pública publicada","concluido":false}]','https://www.conab.gov.br/paa'),
  ('SEAD-PA — Fortalecimento CRAS Municipal','Cofinanciamento estadual para estruturação de CRAS em municípios prioritários','recurso_estadual','SEMAS/Governo do Pará',75000,(CURRENT_DATE + INTERVAL '20 days')::text,'em_risco','[{"item":"Cadastro atualizado no SUASWEB","concluido":true},{"item":"Relatório gestão SUAS 2024","concluido":false},{"item":"Plano municipal assistência social","concluido":false}]','https://www.semas.pa.gov.br'),
  ('SEDUC-PA — Transporte Escolar Rural','Recurso estadual para aquisição de veículo escolar para zona rural','recurso_estadual','SEDUC/Governo do Pará',220000,(CURRENT_DATE + INTERVAL '110 days')::text,'disponivel','[{"item":"Diagnóstico de alunos zona rural","concluido":false},{"item":"Declaração de frota atual","concluido":false}]','https://www.seduc.pa.gov.br'),
  ('Emenda Parlamentar — Infraestrutura Esportiva','Emenda impositiva para construção/reforma de quadra esportiva municipal','recurso_federal','ME/Emenda Parlamentar',350000,(CURRENT_DATE + INTERVAL '150 days')::text,'disponivel','[{"item":"Projeto básico aprovado","concluido":false},{"item":"Área terreno disponível documentada","concluido":false},{"item":"Contato com gabinete parlamentar","concluido":false}]','https://www.me.gov.br')
) AS d(titulo, descricao, tipo, fonte, valor, prazo, status, requisitos, url_edital)
WHERE t.tipo = 'municipio';